name: smart_spend
description: "Smart Spend"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  easy_localization: ^3.0.3
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  flutter_masked_text2: ^0.9.0
  flutter_dotenv: ^5.1.0
  lottie: ^3.3.1
  google_generative_ai: ^0.4.7
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  fl_chart: ^0.71.0
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    - assets/translations/
    - assets/animations/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
